export {default as About } from './About'
export { default as Dish } from './Dish'
export { default as Error } from './Error'
export { default as HomeLayout } from './HomeLayout'
export { default as Landing } from './Landing'
export { default as Newsletter } from './Newsletter'
export { default as HomePage } from './HomePage'